<a href="https://colab.research.google.com/github/AleFax99/DeepLearning_GroupProject/blob/main/DL_Assignment_baseline_2__IN_USE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Loading Dataset

You can download the dataset from {https://darwin.v7labs.com/v7-labs/covid-19-chest-x-ray-dataset?sort=priority\%3Adesc}.
The data entitled as '`darwin dataset pull v7-labs/covid-19-chest-x-ray-dataset:all-images`' will be used in this assignment. All dataset consist of 6504 images from 702 classes. We will extract the images of 4 classes (Bacterial Pneumonia, Viral Pneumonia, No Pneumonia (healthy), Covid-19) and save them as .npy file with the following code:

In [ ]:
#Helloo 
# hellooooo


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
%cd /content/drive/MyDrive/Deep Learning/Deep Learning - Group Project
!pwd

/content/drive/MyDrive/Deep Learning/Deep Learning - Group Project
/content/drive/MyDrive/Deep Learning/Deep Learning - Group Project


In [4]:
import json
import numpy as np
import glob
import pandas as pd

# importing modules
import urllib.request
from PIL import Image
from keras import layers, models
import tensorflow as tf

In [ ]:
# import json
# import numpy as np
# import glob
# import pandas as pd

# # importing modules
# import urllib.request
# from PIL import Image
# from keras import layers, models
# import tensorflow as tf

# # all-images file should be uploaded to the same file
# imageNames = glob.glob("./all-images/*")
# print(type(imageNames))
# print(len(imageNames))
# print(imageNames)

<class 'list'>
6513
['./all-images/1676364.json', './all-images/1676362.json', './all-images/1676365.json', './all-images/1676360.json', './all-images/1676363.json', './all-images/1676367.json', './all-images/1676369.json', './all-images/1676368.json', './all-images/1676361.json', './all-images/1676377.json', './all-images/1676374.json', './all-images/1676375.json', './all-images/1676371.json', './all-images/1676378.json', './all-images/1676376.json', './all-images/1676373.json', './all-images/1676372.json', './all-images/1676370.json', './all-images/1676382.json', './all-images/1676385.json', './all-images/1676379.json', './all-images/1676387.json', './all-images/1676380.json', './all-images/1676384.json', './all-images/1676383.json', './all-images/1676388.json', './all-images/1676389.json', './all-images/1676381.json', './all-images/1676386.json', './all-images/1676392.json', './all-images/1676396.json', './all-images/1676391.json', './all-images/1676393.json', './all-images/1676390.

In [ ]:

# import json
# import numpy as np
# import glob
# import pandas as pd

# # importing modules
# import urllib.request
# from PIL import Image
# from keras import layers, models
# import tensorflow as tf

# # all-images file should be uploaded to the same file
# imageNames = glob.glob("./all-images/*")

# dataset = []
# labels = []

# for i, imName in enumerate(imageNames):

#     # Opening JSON file
#     f = open(imName)
#     data = json.load(f)
#     for j in range(len(data['annotations'])):

#         if 'COVID-19' in (data['annotations'][j]['name']):
#           #load images from url    
#             urllib.request.urlretrieve(data['image']['url'],"img.png")    
#             img = Image.open("img.png")
#             #convert images to grayscale
#             imgGray = img.convert('L')
#             #resize the image (156x156)
#             im = imgGray.resize((156,156), Image.LANCZOS)           
#             label = data['annotations'][j]['name']
#             dataset.append(np.array(im))
#             labels.append(label)
#             print(label)
#             break

#         if 'Viral Pneumonia' in (data['annotations'][j]['name']) \
#             or 'Bacterial Pneumonia' in (data['annotations'][j]['name']) \
#             or 'No Pneumonia (healthy)' in (data['annotations'][j]['name']):
#             #load images from url    
#             urllib.request.urlretrieve(data['image']['url'],"img.png")    
#             img = Image.open("img.png")
#             #convert images to grayscale
#             imgGray = img.convert('L')
#             #resize the image (156x156)
#             im = imgGray.resize((156,156), Image.LANCZOS)           
#             label = data['annotations'][j]['name']
#             dataset.append(np.array(im))
#             labels.append(label)
#             break

# #Convert data shape of (n_of_samples, width, height, 1)
# dataset = np.dstack(dataset)    
# dataset = np.rollaxis(dataset,-1)
# labels = np.array(labels)

# #convert images gray scale to rgb
# data = np.array(layers.Lambda(tf.image.grayscale_to_rgb)(tf.expand_dims(dataset, -1)))

# # save data and labels into a folder
# np.save("./data.npy", data)
# np.save("./labels.npy", labels)

COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
COVID-19
C

Once you save your data, you can load it from your directory.

In [5]:
import numpy as np

data = np.load('./data.npy')
labels = np.load('./labels.npy')

# Preprocessing Steps



## Splitting Data

In [6]:
from sklearn.model_selection import train_test_split
X_train_val, X_test, y_train_val, y_test = train_test_split(data, labels, test_size= 0.2, stratify= labels, random_state=42)

X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size= 0.25, stratify= y_train_val , random_state=42)

print(X_train.shape, X_val.shape, X_test.shape)


(3840, 156, 156, 3) (1280, 156, 156, 3) (1281, 156, 156, 3)


## Normalize Data

In [7]:
# from skimage import io, color
# import matplotlib.pyplot as plt
# %matplotlib inline
# from skimage.filters import threshold_otsu

# data_list = []
# for im in X_train: 
# # read image from disk, provide the correct path 
# # convert to float
#   im = im.astype(float)                
# # normarlize the intensity values a range between 0 and 1
#   im = im-im.min()                    
#   im = im/im.max()
#   data_list.append(im)

# normalize to range 0-1
X_train = X_train / 255.0
X_val = X_val / 255.0
X_test = X_test / 255.0
  
print(X_train[0])

[[[0.14509804 0.14509804 0.14509804]
  [0.16862745 0.16862745 0.16862745]
  [0.18039216 0.18039216 0.18039216]
  ...
  [0.14117647 0.14117647 0.14117647]
  [0.12941176 0.12941176 0.12941176]
  [0.11372549 0.11372549 0.11372549]]

 [[0.15686275 0.15686275 0.15686275]
  [0.17254902 0.17254902 0.17254902]
  [0.18823529 0.18823529 0.18823529]
  ...
  [0.14509804 0.14509804 0.14509804]
  [0.13333333 0.13333333 0.13333333]
  [0.11372549 0.11372549 0.11372549]]

 [[0.16078431 0.16078431 0.16078431]
  [0.17647059 0.17647059 0.17647059]
  [0.19215686 0.19215686 0.19215686]
  ...
  [0.15294118 0.15294118 0.15294118]
  [0.13333333 0.13333333 0.13333333]
  [0.10980392 0.10980392 0.10980392]]

 ...

 [[0.09019608 0.09019608 0.09019608]
  [0.10588235 0.10588235 0.10588235]
  [0.10196078 0.10196078 0.10196078]
  ...
  [0.12156863 0.12156863 0.12156863]
  [0.11764706 0.11764706 0.11764706]
  [0.11764706 0.11764706 0.11764706]]

 [[0.09019608 0.09019608 0.09019608]
  [0.10980392 0.10980392 0.10980392]


In [8]:
print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

(3840, 156, 156, 3)
(1280, 156, 156, 3)
(1281, 156, 156, 3)


In [18]:
type(y_train)

numpy.ndarray

In [19]:
y_train.shape

(3840,)

In [20]:
y_train.dtype

dtype('<U22')

In [9]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# enc = OneHotEncoder(handle_unknown='ignore')
# y_train_enc = enc.fit_transform(y_train)

# print(y_train_enc[0])

from sklearn import preprocessing
le = preprocessing.LabelEncoder()
y_train = le.fit_transform(y_train)
y_val = le.transform(y_val)
y_test = le.transform(y_test)


In [34]:
le.classes_

array(['Bacterial Pneumonia', 'COVID-19', 'No Pneumonia (healthy)',
       'Viral Pneumonia'], dtype='<U22')

In [10]:
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(y_train)
y_val = to_categorical(y_val)
y_test = to_categorical(y_test)

# Create Baseline Model

In [11]:
from tensorflow.keras import Sequential
from tensorflow.keras import layers


model = Sequential()
model.add(layers.Conv2D(64, (3,3), activation='relu', 
                        input_shape = (156,156,3), padding="same"))
model.add(layers.Conv2D(32, (3,3), activation='relu', padding="same"))
model.add(layers.MaxPooling2D(pool_size=(2, 2), padding="same"))
model.add(layers.Conv2D(64, (3,3), activation='relu', padding="same"))
model.add(layers.Conv2D(32, (3,3), activation='relu', padding="same"))
model.add(layers.MaxPooling2D(pool_size=(2, 2), padding="same"))
model.add(layers.Flatten())
model.add(layers.Dense(32, activation="relu"))
model.add(layers.Dense(32, activation="relu"))
model.add(layers.Dense(4, activation="softmax"))


In [12]:
model.build()
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 156, 156, 64)      1792      
                                                                 
 conv2d_1 (Conv2D)           (None, 156, 156, 32)      18464     
                                                                 
 max_pooling2d (MaxPooling2D  (None, 78, 78, 32)       0         
 )                                                               
                                                                 
 conv2d_2 (Conv2D)           (None, 78, 78, 64)        18496     
                                                                 
 conv2d_3 (Conv2D)           (None, 78, 78, 32)        18464     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 39, 39, 32)       0         
 2D)                                                    

In [13]:
model.compile(
    optimizer='adam',
    loss=tf.keras.losses.CategoricalCrossentropy(),
    metrics=['accuracy']
)
history = model.fit(
    X_train,
    y_train,
    batch_size=32,
    epochs=10,
    validation_data=(X_val, y_val)
)



Epoch 1/10
120/120 [==============================] - 22s 73ms/step - loss: 0.8509 - accuracy: 0.6375 - val_loss: 0.6358 - val_accuracy: 0.7531
Epoch 2/10
120/120 [==============================] - 8s 68ms/step - loss: 0.6445 - accuracy: 0.7411 - val_loss: 0.6105 - val_accuracy: 0.7453
Epoch 3/10
120/120 [==============================] - 7s 62ms/step - loss: 0.5503 - accuracy: 0.7716 - val_loss: 0.5980 - val_accuracy: 0.7609
Epoch 4/10
120/120 [==============================] - 8s 63ms/step - loss: 0.5124 - accuracy: 0.7854 - val_loss: 0.6016 - val_accuracy: 0.7602
Epoch 5/10
120/120 [==============================] - 7s 62ms/step - loss: 0.4682 - accuracy: 0.8052 - val_loss: 0.6237 - val_accuracy: 0.7492
Epoch 6/10
120/120 [==============================] - 8s 64ms/step - loss: 0.4076 - accuracy: 0.8315 - val_loss: 0.7192 - val_accuracy: 0.7531
Epoch 7/10
120/120 [==============================] - 7s 62ms/step - loss: 0.3471 - accuracy: 0.8635 - val_loss: 0.6587 - val_accuracy: 0.755

# Analyze the performance of the baseline model

In [14]:
test_loss, test_acc = model.evaluate(X_test, y_test)

41/41 [==============================] - 1s 23ms/step - loss: 0.9022 - accuracy: 0.7518


# Plots

## Training and validation losses and accuracies on the training and validation set

## Receiver Operator Characteristic (ROC) curve with the Area under the Curve (AUC) score

## Confusion matrix for the validation and test set

# Adapting/fine-tuning the network

# Transfer Learning